#!/usr/bin/env bash
set -e

echo "Starting Floci..."
# Spin up Floci via Docker Compose or CLI
docker compose up -d floci

# Wait a brief moment for Floci to be ready (it starts in milliseconds!)
echo " Waiting for environment availability..."
until curl -s http://localhost:4566/health | grep -q "ok"; do sleep 0.5; done

echo "📦 Packaging Python Lambda function..."
zip -j lambda.zip src/lambda_function.py

echo "Initializing Infrastructure via Terraform..."
terraform init
terraform apply -auto-approve

# Extract the local API Gateway URL generated by Terraform
API_URL=$(terraform output -raw api_endpoint_url)

echo "Running API Endpoint Tests against $API_URL..."
# Test POST (Create)
curl -X POST "$API_URL/books/1" -H "Content-Type: application/json" -d '{"title": "The Phoenix Project", "author": "Gene Kim"}'
# Test GET (Read)
curl -X GET "$API_URL/books/1"

echo "Tearing down local infrastructure..."
terraform destroy -auto-approve
docker compose down

echo "Pipeline successfully completed!"